defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: gminer_development

test:
  <<: *defaults
  database: gminer_test

# set these environment variables on your prod server
production:
  host: production
  port: 27018
  database: gminer_production